version: "3.3"

services:
    front:
        build:
            context: ./front
            dockerfile: ./Dockerfile
        ports: 
            - "8000:80"
        image: front
    
    back:
        build:
            context: ./back
            dockerfile: ./Dockerfile
        ports: 
            - "9000:8080"
        image: back

    db:
        image: mariadb
        restart: always
        build:
            context: ./db
            dockerfile: ./Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: example
        ports: 
            - "3306:3306"
        volumes:
        - ./db/sql:/var/db