version: "3.3"

services:
    front:
        build:
            context: ./front
            dockerfile: ./Dockerfile
        ports: 
            - "8080:80"
        image: front
    
    back:
        build:
            context: ./back
            dockerfile: ./Dockerfile
        ports: 
            - "9000:8080"
        image: back

    db:
        image: bitnami/mariadb
        container_name: photo_db
        restart: always
        environment:
            MARIADB_DATABASE: 'photodb'
            MARIADB_USER: 'photodb'
            MARIADB_PASSWORD: 'photodb'
            MARIADB_ROOT_PASSWORD: 'photodb'
        ports: 
            - "3316:3306"
        volumes: 
            - ./db/sql:/docker-entrypoint-initdb.d